import React from 'react'
import CIcon from '@coreui/icons-react'
import { cilPen, cilTrash } from '@coreui/icons'

export const funcionarios = [
  {
    id: 0,
    nome: 'Goreth Manuel',
    genero: 'Feminino',
    cargo: 'Coordenadora',
    salario: '70.000kz',
    iconPen: <CIcon icon={cilPen} />,
    iconTrash: <CIcon icon={cilTrash} />,
  },
  {
    id: 1,
    nome: 'Margarida André',
    genero: 'Feminino',
    cargo: 'Professora',
    salario: '55.000kz',
    iconPen: <CIcon icon={cilPen} />,
    iconTrash: <CIcon icon={cilTrash} />,
  },
  {
    id: 2,
    nome: 'Benedito Vieiras',
    genero: 'Masculino',
    cargo: 'Professor',
    salario: '35.000kz',
    iconPen: <CIcon icon={cilPen} />,
    iconTrash: <CIcon icon={cilTrash} />,
  },

  {
    id: 3,
    nome: 'Luzia José',
    genero: 'Feminino',
    cargo: 'Professora',
    salario: '48.000kz',
    iconPen: <CIcon icon={cilPen} />,
    iconTrash: <CIcon icon={cilTrash} />,
  },
  {
    id: 4,
    nome: 'Benedito Vieiras',
    genero: 'Masculino',
    cargo: 'Professor',
    salario: '35.000kz',
    iconPen: <CIcon icon={cilPen} />,
    iconTrash: <CIcon icon={cilTrash} />,
  },
  {
    id: 5,
    nome: 'Suzana Pereira',
    genero: 'Feminino',
    cargo: 'Professora',
    salario: '32.000kz',
    iconPen: <CIcon icon={cilPen} />,
    iconTrash: <CIcon icon={cilTrash} />,
  },
  {
    id: 6,
    nome: 'Augusto João',
    genero: 'Feminino',
    cargo: 'Professora',
    salario: '23.000kz',
    iconPen: <CIcon icon={cilPen} />,
    iconTrash: <CIcon icon={cilTrash} />,
  },
  {
    id: 7,
    nome: 'Alexandre de Jesus',
    genero: 'Masculino',
    cargo: 'Professor',
    salario: '53.000kz',
    iconPen: <CIcon icon={cilPen} />,
    iconTrash: <CIcon icon={cilTrash} />,
  },
  {
    id: 8,
    nome: 'Augusto João',
    genero: 'Feminino',
    cargo: 'Professora',
    salario: '23.000kz',
    iconPen: <CIcon icon={cilPen} />,
    iconTrash: <CIcon icon={cilTrash} />,
  },
]
